spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/repairdesk
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

jwt.secret=RepairDeskSuperSecretKeyForJWT256BitMinimumLength!!
jwt.expiration-ms=86400000

minio.url=http://${MINIO_HOST:localhost}:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=ticket-media
minio.public-url=${MINIO_PUBLIC_URL:http://localhost:9000}

encryption.aes-key=RepairDeskAES256EncryptionSecretKey2024!

business.hours.open=8
business.hours.close=22

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

spring.jackson.time-zone=Europe/Moscow

server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

# ===============================
# Actuator (??????????)
# ===============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized

# ===============================
# Logging
# ===============================
logging.level.com.Wearly.app=DEBUG
logging.level.com.Wearly.app.controller=DEBUG
logging.level.com.Wearly.app.service=DEBUG
logging.level.com.Wearly.app.config.security=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{40} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{40} - %msg%n
logging.file.name=logs/clothing-store.log
